const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const seeded = [
 {id:'v1',name:'Aarav Industrial Solutions Pvt. Ltd.',gst:'27AAQCA1234F1ZP',package:'Tender #S26-104',score:94,risk:'Low',status:'Ready for review',docs:8,updated:'Today, 10:42 AM',flags:[],audit:['Package submitted · Today, 10:36 AM','AI verification completed · Today, 10:42 AM']},
 {id:'v2',name:'NexGen Infra Systems',gst:'29AABCN5521K1ZQ',package:'Tender #S26-104',score:82,risk:'Medium',status:'Needs review',docs:6,updated:'Today, 9:18 AM',flags:['ITR FY 2024–25 is missing'],audit:['Package submitted · Today, 9:10 AM','AI found 1 discrepancy · Today, 9:18 AM']},
 {id:'v3',name:'Pragati Engineering Works',gst:'07AAECP8750L1ZV',package:'Tender #S26-104',score:97,risk:'Low',status:'Approved',docs:8,updated:'Yesterday',flags:[],audit:['Approved by R. Sharma · Yesterday, 4:32 PM']},
 {id:'v4',name:'Vertex Supply Co.',gst:'33AATFV9284H1ZS',package:'Tender #S26-104',score:61,risk:'High',status:'Flagged',docs:5,updated:'Yesterday',flags:['PAN name does not match GST registration','Bank proof is unreadable'],audit:['Flagged by R. Sharma · Yesterday, 2:08 PM']}
];
let bidders = JSON.parse(localStorage.getItem('procuresure-bidders') || 'null') || seeded;
let files=[]; let selectedId=null;
function save(){localStorage.setItem('procuresure-bidders',JSON.stringify(bidders))}
function nav(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#page-title').textContent=view==='home'?'Procurement, verified.':view==='vendor'?'Vendor workspace':'Officer review desk';$('.sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
$$('#nav button').forEach(b=>b.onclick=()=>nav(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));$('#menu').onclick=()=>$('.sidebar').classList.toggle('open');
function typeFor(name, forced){if(forced&&forced!=='Auto-detect')return forced;let n=name.toLowerCase();if(n.includes('gst'))return 'GST Registration Certificate';if(n.includes('pan'))return 'PAN Card';if(n.includes('udyam')||n.includes('msme'))return 'Udyam Registration';if(n.includes('itr')||n.includes('tax'))return 'Income Tax Return';if(n.includes('bank'))return 'Bank Account Proof';if(n.includes('technical'))return 'Technical Proposal';return 'Supporting document'}
function addFiles(list,forced){[...list].slice(0,20-files.length).forEach(f=>files.push({name:f.name,size:f.size,type:typeFor(f.name,forced)}));renderFiles();if(list.length)toast(`${Math.min(list.length,20)} document${list.length!==1?'s':''} added to your package`)}
function renderFiles(){$('#file-count').textContent=`${files.length} file${files.length!==1?'s':''}`;$('#verify').disabled=!files.length;$('#file-list').innerHTML=files.length?files.map((f,i)=>`<div class="file-row"><div class="file-icon">${f.name.split('.').pop().toUpperCase().slice(0,4)}</div><div class="file-info"><b>${esc(f.name)}</b><small>${f.type} · ${Math.max(1,Math.round(f.size/1024))} KB</small></div><span class="doc-label">Classify on scan</span><button class="row-action remove" onclick="removeFile(${i})">Remove</button></div>`).join(''):'<div class="empty">Your uploaded documents will appear here.</div>'}
function esc(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function removeFile(i){files.splice(i,1);renderFiles()}window.removeFile=removeFile;
$('#bulk-input').onchange=e=>addFiles(e.target.files);$('#single-input').onchange=e=>{addFiles(e.target.files,$('#doc-type').value);e.target.value=''};let drop=$('#dropzone');['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>addFiles(e.dataTransfer.files));
$('#verify').onclick=()=>{let names=files.map(f=>f.name.toLowerCase()), found=t=>names.some(n=>n.includes(t));let missing=[];if(!found('gst'))missing.push('GST certificate was not confidently identified');if(!found('pan'))missing.push('PAN card was not confidently identified');let score=Math.max(62,Math.min(98,78+files.length*2-missing.length*6));let risk=score>=90?'Low':score>=75?'Medium':'High';$('#step2').classList.add('done');$('#step3').classList.add('done');$('#report').classList.remove('hidden');$('#report').innerHTML=`<div class="report-top"><div class="score-ring" style="--score:${score * 3.6}deg"><b>${score}%</b></div><div><h3>AI verification report <span class="risk ${risk.toLowerCase()}">${risk} risk</span></h3><p>Simulated OCR, cross-document matching, and mock government validation completed.</p></div><button class="secondary download" id="download">Download report</button></div><div class="report-grid"><div><h3>Extracted & checked</h3><div class="check-item"><span class="ok">✓</span> ${files.length} documents classified and indexed</div><div class="check-item"><span class="ok">✓</span> GSTIN format and PAN linkage <small>(mock API)</small></div><div class="check-item"><span class="ok">✓</span> Udyam/MSME registry check <small>(mock API)</small></div><div class="check-item"><span class="ok">✓</span> Income tax return status <small>(mock API)</small></div></div><div><h3>Review attention</h3>${missing.length?missing.map(x=>`<div class="check-item"><span class="warn">!</span> ${x}</div>`).join(''):'<div class="check-item"><span class="ok">✓</span> No material discrepancies detected</div>'}<div class="check-item"><span class="warn">!</span> Government integrations are mock/prototype checks</div></div></div>`;$('#download').onclick=downloadReport;toast('Verification complete — report is ready for review');$('#report').scrollIntoView({behavior:'smooth',block:'nearest'})};
function downloadReport(){let text=`PROCURESURE — PROTOTYPE VERIFICATION REPORT\nGenerated: ${new Date().toLocaleString()}\n\nDocuments (${files.length}):\n${files.map(f=>`- ${f.name}: ${f.type}`).join('\n')}\n\nNote: AI/OCR and government verification results are simulated for this local demo.`;let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download='procuresure-verification-report.txt';a.click();URL.revokeObjectURL(a.href);toast('Report downloaded')}
function renderBidders(){let q=$('#search').value.toLowerCase(),s=$('#status-filter').value,r=$('#risk-filter').value;let rows=bidders.filter(b=>(s==='All'||b.status===s)&&(r==='All'||b.risk===r)&&(`${b.name} ${b.gst} ${b.package}`).toLowerCase().includes(q));$('#bidder-list').innerHTML=rows.length?rows.map(b=>`<tr onclick="selectBidder('${b.id}')"><td><span class="company">${b.name}</span><span class="sub">${b.gst}</span></td><td>${b.package}<span class="sub">${b.docs} documents</span></td><td><span class="score">${b.score}%</span></td><td><span class="risk ${b.risk.toLowerCase()}">${b.risk}</span></td><td><span class="status ${b.status.replace(' ','-')}">${b.status}</span></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No bidders match these filters.</td></tr>';$('#stat-bidders').textContent=bidders.length;$('#stat-score').textContent=Math.round(bidders.reduce((a,b)=>a+b.score,0)/bidders.length)+'%';$('#stat-review').textContent=bidders.filter(b=>b.status==='Ready for review'||b.status==='Needs review').length}
function selectBidder(id){selectedId=id;let b=bidders.find(x=>x.id===id);$('#review-panel').innerHTML=`<span class="eyebrow">BIDDER RECORD</span><h3>${b.name}</h3><div class="detail-meta">${b.gst} · ${b.package}<br>Updated ${b.updated}</div><div class="detail-score"><div><b>${b.score}% compliance</b><div class="detail-meta">${b.docs} documents analyzed</div></div><span class="risk ${b.risk.toLowerCase()}">${b.risk} risk</span></div><div><b>Verification findings</b>${b.flags.length?b.flags.map(f=>`<div class="check-item"><span class="warn">!</span> ${f}</div>`).join(''):'<div class="check-item"><span class="ok">✓</span> No material discrepancies</div>'}<div class="check-item"><span class="ok">✓</span> Mock government checks recorded</div></div><div class="action-grid"><button onclick="decide('Approved')">Approve</button><button onclick="decide('Needs review')">Request review</button><button onclick="decide('Flagged')">Flag bidder</button></div><div class="audit"><h4>AUDIT TRAIL</h4>${b.audit.map(a=>`<div class="audit-item">${a}</div>`).join('')}</div>`}window.selectBidder=selectBidder;
function decide(status){let b=bidders.find(x=>x.id===selectedId);b.status=status;b.audit.unshift(`${status==='Approved'?'Approved':status==='Flagged'?'Flagged':'Review requested'} by Demo Officer · ${new Date().toLocaleString()}`);if(status==='Flagged'&&!b.flags.length)b.flags.push('Officer flagged package for manual review');save();renderBidders();selectBidder(b.id);toast(`Bidder marked ${status.toLowerCase()}`)}window.decide=decide;
['#search','#status-filter','#risk-filter'].forEach(x=>$(x).addEventListener(x==='#search'?'input':'change',renderBidders));$('#seed').onclick=()=>{bidders=structuredClone(seeded);save();renderBidders();$('#review-panel').innerHTML='<div class="empty">Demo data restored. Select a bidder to view the verification record.</div>';toast('Demo records restored')};function toast(m){let t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}renderFiles();renderBidders();
